fix: input 수정

diff --git a/.github/workflows/deploy-service.yml b/.github/workflows/deploy-service.yml
--- a/.github/workflows/deploy-service.yml
+++ b/.github/workflows/deploy-service.yml
@@ -26,6 +26,13 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Verify SSH Key Presence
+        run: |
+          if [ -z "${{ secrets.key }}" ]; then
+            echo "SSH key is missing!"
+            exit 1
+          fi
+          echo "${{ secrets.key }}" | grep "BEGIN" || { echo "SSH key format is incorrect!"; exit 1; }
       # 1. Sparse checkout으로 하위 디렉토리만 체크아웃
       - name: Checkout repository with sparse checkout
         uses: actions/checkout@v3
@@ -53,12 +60,12 @@ jobs:
       - name: Deploy ${{ inputs.service }} to server
         uses: appleboy/ssh-action@v1.1.0
         with:
-          host: ${{ secrets.host }}
-          username: ${{ secrets.user }}
-          key: ${{ secrets.key }}
-          port: ${{ secrets.port }}
+          host: ${{ secrets.CONSOLE_SERVER_HOST }}
+          username: ${{ secrets.SSH_USER }}
+          key: ${{ secrets.SSH_KEY }}
+          port: ${{ secrets.SSH_PORT }}
           script: |
             cd /home/watchducks/app
-            echo "${{ secrets.env }}" > .env
+            echo "${{ secrets.CONSOLE_SERVER_ENV }}" > .env
             docker pull ghcr.io/${{ github.repository_owner }}/${{ inputs.service }}:latest
             docker-compose up -d
